#!/usr/bin/env python3
"""
SCONS BUILD INTEGRATION: Generate orca_version.gen.cpp with baked-in version
This is called during SCons build to embed the GitHub release version into the binary
"""

import os
import subprocess
import sys

def get_build_version():
    """Get version for this build (from GitHub Actions or git)"""
    
    # Priority 1: GitHub Actions environment (for release builds)
    github_ref = os.getenv('GITHUB_REF', '')
    if github_ref.startswith('refs/tags/'):
        # This is a tagged release build
        tag = github_ref.replace('refs/tags/', '').lstrip('v')
        print(f"ORCA BUILD: Version from GitHub tag: {tag}")
        return tag
    
    # Priority 2: Manual override
    orca_version = os.getenv('ORCA_VERSION')
    if orca_version:
        print(f"ORCA BUILD: Version from ORCA_VERSION env: {orca_version}")
        return orca_version
    
    # Priority 3: Local git tag (for tagged commits)
    try:
        result = subprocess.run(
            ['git', 'describe', '--exact-match', '--tags', 'HEAD'],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            tag = result.stdout.strip().lstrip('v')
            print(f"ORCA BUILD: Version from local git tag: {tag}")
            return tag
    except:
        pass
    
    # Priority 4: Development build with SHA
    try:
        result = subprocess.run(
            ['git', 'rev-parse', '--short=8', 'HEAD'],
            capture_output=True, text=True, check=False
        )
        if result.returncode == 0:
            sha = result.stdout.strip()
            version = f"0.01.{sha}"
            print(f"ORCA BUILD: Development version from SHA: {version}")
            return version
    except:
        pass
    
    # Fallback
    print("ORCA BUILD: WARNING - Using fallback version")
    return "1.0.0-dev"

def generate_version_cpp(version, output_path):
    """Generate C++ file with embedded version constant"""
    
    cpp_content = f'''// AUTO-GENERATED by generate_orca_version.py during SCons build
// DO NOT EDIT - This file is regenerated on every build

#include "core/version.h"

// Orca Engine version embedded at build time
// This version comes from the GitHub release tag or git commit
const char *const ORCA_VERSION_STRING = "{version}";
const char *const ORCA_VERSION_FULL = "Orca Engine v{version}";

// For runtime version detection
const char *get_orca_version() {{
    return ORCA_VERSION_STRING;
}}
'''
    
    with open(output_path, 'w') as f:
        f.write(cpp_content)
    
    print(f"✅ Generated: {output_path}")
    print(f"   Embedded version: {version}")

if __name__ == "__main__":
    # Get version for this build
    version = get_build_version()
    
    # Output path for generated C++ file
    output_path = os.path.join(os.path.dirname(__file__), 'core', 'orca_version.gen.cpp')
    
    generate_version_cpp(version, output_path)
    
    print(f"\n✅ Orca version embedded in binary: {version}")
    print("📦 This version will be compiled into the Godot executable")
