#!/usr/bin/env python3
"""
PRODUCTION BUILD SCRIPT: Generate version files for Orca Engine releases
This should be called during GitHub Actions builds to embed the release version
"""

import os
import sys
import subprocess
import json

def get_release_version():
    """Get the version for this release build"""
    
    # Method 1: GitHub Actions - get from GITHUB_REF (for tagged releases)
    github_ref = os.getenv('GITHUB_REF', '')
    if github_ref.startswith('refs/tags/'):
        tag = github_ref.replace('refs/tags/', '')
        if tag.startswith('v'):
            tag = tag[1:]  # Remove v prefix
        print(f"BUILD VERSION: From GitHub tag: {tag}")
        return tag
    
    # Method 2: Environment variable override
    env_version = os.getenv('ORCA_VERSION')
    if env_version:
        print(f"BUILD VERSION: From environment: {env_version}")
        return env_version
    
    # Method 3: Git tag (for manual builds)
    try:
        result = subprocess.run([
            'git', 'describe', '--exact-match', '--tags', 'HEAD'
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            tag = result.stdout.strip()
            if tag.startswith('v'):
                tag = tag[1:]
            print(f"BUILD VERSION: From git tag: {tag}")
            return tag
    except Exception as e:
        print(f"BUILD VERSION: Git tag detection failed: {e}")
    
    # Method 4: Development build with git SHA
    try:
        result = subprocess.run([
            'git', 'rev-parse', '--short=8', 'HEAD'
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            sha = result.stdout.strip()
            version = f"0.01.{sha}"
            print(f"BUILD VERSION: Development build: {version}")
            return version
    except Exception as e:
        print(f"BUILD VERSION: Git SHA detection failed: {e}")
    
    # Fallback
    return "1.0.0-unknown"

def generate_version_files(version):
    """Generate version files for both backend and frontend"""
    
    # 1. Create ORCA_VERSION.txt for runtime detection
    version_txt_path = os.path.join(os.path.dirname(__file__), 'ORCA_VERSION.txt')
    with open(version_txt_path, 'w') as f:
        f.write(version)
    print(f"✅ Created: {version_txt_path} -> {version}")
    
    # 2. Update version.py with the release version
    version_py_path = os.path.join(os.path.dirname(__file__), 'version.py')
    
    # Read current version.py
    if os.path.exists(version_py_path):
        with open(version_py_path, 'r') as f:
            content = f.read()
    else:
        content = 'version = "1.0.0"\n'
    
    # Replace version line
    lines = content.split('\n')
    for i, line in enumerate(lines):
        if line.strip().startswith('version') and '=' in line:
            lines[i] = f'version = "{version}"  # Auto-generated by build system'
            break
    else:
        # Add version line if not found
        lines.insert(0, f'version = "{version}"  # Auto-generated by build system')
    
    # Write updated version.py
    with open(version_py_path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"✅ Updated: {version_py_path} -> version = \"{version}\"")
    
    # 3. Create C++ header file for frontend
    cpp_header_path = os.path.join(os.path.dirname(__file__), 'editor', 'orca_version.gen.h')
    cpp_content = f'''// AUTO-GENERATED by generate_version_header.py
// DO NOT EDIT MANUALLY

#pragma once

#define ORCA_VERSION_STRING "{version}"
#define ORCA_VERSION_MAJOR {version.split('.')[0] if '.' in version else '1'}
#define ORCA_VERSION_MINOR {version.split('.')[1] if version.count('.') >= 1 else '0'}

// For distributed binaries to identify their GitHub release version
static const char* get_orca_version() {{
    return "{version}";
}}
'''
    
    # Ensure editor directory exists
    os.makedirs(os.path.dirname(cpp_header_path), exist_ok=True)
    with open(cpp_header_path, 'w') as f:
        f.write(cpp_content)
    print(f"✅ Created: {cpp_header_path} -> {version}")
    
    # 4. Create version info JSON for advanced scenarios
    version_json_path = os.path.join(os.path.dirname(__file__), 'version_info.json')
    version_info = {
        "version": version,
        "build_timestamp": int(__import__('time').time()),
        "build_system": "GitHub Actions" if os.getenv('GITHUB_ACTIONS') else "Manual",
        "platform": sys.platform,
        "created_by": "generate_version_header.py"
    }
    
    with open(version_json_path, 'w') as f:
        json.dump(version_info, f, indent=2)
    print(f"✅ Created: {version_json_path}")

def main():
    print("🔧 ORCA ENGINE VERSION GENERATOR")
    print("=" * 50)
    
    version = get_release_version()
    print(f"📦 Release Version: {version}")
    
    generate_version_files(version)
    
    print("\n✅ Version files generated successfully!")
    print("📋 Files created/updated:")
    print("  - ORCA_VERSION.txt (runtime detection)")
    print("  - version.py (backend detection)")  
    print("  - editor/orca_version.gen.h (C++ frontend)")
    print("  - version_info.json (build metadata)")
    
    print(f"\n🎯 NEXT STEPS:")
    print("1. Include this script in your GitHub Actions workflows")
    print("2. Run before building the binary")
    print("3. Distributed apps will now know their exact GitHub release version")

if __name__ == "__main__":
    main()