'use client';

import React, { useState } from 'react';
import { useGame } from '../game/GameContext';
import { Resources, ResourceIncome } from '../game/types';

interface ResourceDisplayProps {
  name: string;
  icon: string;
  amount: number;
  income: number;
  description: string;
}

function ResourceDisplay({ name, icon, amount, income, description }: ResourceDisplayProps) {
  const [showTooltip, setShowTooltip] = useState(false);

  return (
    <div 
      className="relative flex flex-col items-center px-4 py-2 bg-gray-800 rounded-lg hover:bg-gray-700 transition-colors cursor-help"
      onMouseEnter={() => setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
    >
      <div className="flex items-center gap-2">
        <span className="text-2xl">{icon}</span>
        <div className="flex flex-col">
          <span className="text-sm font-semibold text-gray-300">{name}</span>
          <span className="text-lg font-bold text-white">{Math.floor(amount)}</span>
        </div>
      </div>
      <div className="flex items-center gap-1 mt-1">
        <span className="text-xs text-green-400">+{income}/sec</span>
      </div>

      {/* Tooltip */}
      {showTooltip && (
        <div className="absolute top-full mt-2 z-50 w-64 p-3 bg-gray-900 border-2 border-gray-700 rounded-lg shadow-xl">
          <h4 className="font-bold text-white mb-2">{icon} {name}</h4>
          <p className="text-sm text-gray-300 mb-2">{description}</p>
          <div className="text-xs text-gray-400">
            <div className="flex justify-between">
              <span>Current:</span>
              <span className="text-white font-semibold">{Math.floor(amount)}</span>
            </div>
            <div className="flex justify-between">
              <span>Income:</span>
              <span className="text-green-400 font-semibold">+{income} per second</span>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

export function ResourceBar() {
  const { gameState } = useGame();

  const resourceInfo = {
    gold: {
      icon: '💰',
      description: 'Used for training units and building structures. Generated by Gold Mines.',
      uses: ['Training units', 'Building structures', 'Research upgrades']
    },
    wood: {
      icon: '🪵',
      description: 'Required for most buildings and siege equipment. Generated by Lumber Mills.',
      uses: ['Building structures', 'Crafting siege weapons', 'Ship construction']
    },
    stone: {
      icon: '🪨',
      description: 'Used for defensive structures and advanced buildings. Generated by Quarries.',
      uses: ['Defensive walls', 'Castle upgrades', 'Advanced buildings']
    },
    food: {
      icon: '🍖',
      description: 'Required to sustain your army and population. Generated by Farms.',
      uses: ['Training units', 'Population support', 'Army maintenance']
    }
  };

  return (
    <div className="w-full bg-gray-900 border-b-2 border-gray-700 p-4">
      <div className="max-w-7xl mx-auto">
        <div className="flex justify-between items-center">
          <h2 className="text-xl font-bold text-white mb-2">Resources</h2>
          <div className="text-sm text-gray-400">
            💡 Hover over resources for details
          </div>
        </div>
        <div className="grid grid-cols-4 gap-4">
          <ResourceDisplay 
            name="Gold"
            icon={resourceInfo.gold.icon}
            amount={gameState.resources.gold}
            income={gameState.income.gold}
            description={resourceInfo.gold.description}
          />
          <ResourceDisplay 
            name="Wood"
            icon={resourceInfo.wood.icon}
            amount={gameState.resources.wood}
            income={gameState.income.wood}
            description={resourceInfo.wood.description}
          />
          <ResourceDisplay 
            name="Stone"
            icon={resourceInfo.stone.icon}
            amount={gameState.resources.stone}
            income={gameState.income.stone}
            description={resourceInfo.stone.description}
          />
          <ResourceDisplay 
            name="Food"
            icon={resourceInfo.food.icon}
            amount={gameState.resources.food}
            income={gameState.income.food}
            description={resourceInfo.food.description}
          />
        </div>
      </div>
    </div>
  );
}
