#!/bin/bash

# Godot AI Database Server - Cloud Run Deployment Script

# Configuration
# PROJECT_ID must be provided as arg or via GCP_PROJECT_ID env var.
if [ -n "$1" ]; then
    PROJECT_ID="$1"
elif [ -n "$GCP_PROJECT_ID" ]; then
    PROJECT_ID="$GCP_PROJECT_ID"
else
    echo "❌ Error: GCP project id not provided."
    echo "Usage: ./deploy.sh <GCP_PROJECT_ID> [SERVICE_NAME]"
    echo "       ./deploy.sh my-project-id                           # Uses default godot-database-server"
    echo "       ./deploy.sh my-project-id my-custom-database-server # Uses custom service name"
    echo "   OR: Set GCP_PROJECT_ID and/or SERVICE_NAME environment variables"
    exit 1
fi

# Handle optional service name parameter or environment variable
if [ -n "$2" ]; then
    SERVICE_NAME="$2"  # Use provided service name
elif [ -n "$SERVICE_NAME" ]; then
    # Use environment variable if set
    echo "📋 Using SERVICE_NAME from environment: $SERVICE_NAME"
else
    SERVICE_NAME="godot-database-server"  # Default service name
fi

echo "📋 DEPLOYMENT STRATEGY:"
echo "   🗄️  Service: $SERVICE_NAME (3D model retrieval from Supabase)"
echo "   🌐 Purpose: Fetch and serve 3D models generated by GPU server"
echo "   📡 Connects to: Supabase (configured via SUPABASE_URL env var)"
REGION="us-central1"
IMAGE_NAME="gcr.io/${PROJECT_ID}/${SERVICE_NAME}"

echo "🚀 Deploying Godot AI Database Server to Google Cloud Run"
echo "Project ID: ${PROJECT_ID}"
echo "Service Name: ${SERVICE_NAME}"
echo "Region: ${REGION}"

# Always run from this script's directory so build context is only the database_server/
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
pushd "$SCRIPT_DIR" >/dev/null

# Check if gcloud is authenticated
if ! gcloud auth list --filter=status:ACTIVE --format="value(account)" | grep -q .; then
    echo "❌ Error: No active gcloud authentication found."
    echo "Please run: gcloud auth login"
    exit 1
fi

# Set the project
echo "📋 Setting GCP project..."
gcloud config set project ${PROJECT_ID}

# Enable required APIs
echo "🔧 Enabling required APIs..."
gcloud services enable cloudbuild.googleapis.com
gcloud services enable run.googleapis.com
gcloud services enable containerregistry.googleapis.com
gcloud services enable secretmanager.googleapis.com

# Extract version information from version.py for build-time injection
echo "📋 Extracting versions from version.py..."
if [ -f "../../extract_versions.py" ] && [ -f "../../version.py" ]; then
    # Use the extraction script for reliable version parsing
    eval $(python3 ../../extract_versions.py env_vars)
    echo "📋 Extracted versions: Backend=$BACKEND_VERSION, API=$API_VERSION, Frontend=$FRONTEND_VERSION, Orca=$ORCA_VERSION"
else
    echo "⚠️  extract_versions.py or version.py not found, using default versions"
    BACKEND_VERSION="1.0.0"
    API_VERSION="1.0"
    FRONTEND_VERSION="1.0.0"
    ORCA_VERSION="1.0.0"
fi

# Build and push the container image
echo "🏗️  Building container image (scoped to database_server/ context)..."
echo "📋 Versions will be injected via environment variables during deployment"
gcloud builds submit --tag ${IMAGE_NAME}

# Upload secrets to GCP Secret Manager if .env exists
SECRET_REFS=""
if [ -f ".env" ]; then
    echo "📋 Found .env file, uploading secrets to GCP Secret Manager..."
    
    # Get project number for service account
    PROJECT_NUMBER=$(gcloud projects describe ${PROJECT_ID} --format="value(projectNumber)")
    COMPUTE_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"
    
    echo "🔧 Granting Secret Manager access to Cloud Run service account..."
    gcloud projects add-iam-policy-binding ${PROJECT_ID} \
        --member="serviceAccount:${COMPUTE_SA}" \
        --role="roles/secretmanager.secretAccessor"
    
    # CRITICAL: Force DEV_MODE=false for cloud deployments
    echo "🔧 Overriding DEV_MODE=false for cloud deployment..."
    if echo -n "false" | gcloud secrets create "DATABASE_DEV_MODE" --data-file=- --replication-policy="automatic" 2>/dev/null || \
       echo -n "false" | gcloud secrets versions add "DATABASE_DEV_MODE" --data-file=- 2>/dev/null; then
        echo "✅ DEV_MODE set to false for production"
    fi
    
    # Read .env and create secrets with DATABASE_ prefix to avoid conflicts
    SECRET_NAMES=("DATABASE_DEV_MODE")
    while IFS='=' read -r key value || [ -n "$key" ]; do
        # Skip comments and empty lines
        [[ $key =~ ^#.*$ ]] && continue
        [[ -z "$key" ]] && continue
        
        # Add DATABASE_ prefix to avoid conflicts with main backend secrets
        secret_name="DATABASE_${key}"
        
        # Remove any quotes from value
        value=$(echo "$value" | sed 's/^"//;s/"$//')
        
        echo "🔐 Creating/updating secret: $secret_name"
        if echo -n "$value" | gcloud secrets create "$secret_name" --data-file=- --replication-policy="automatic" 2>/dev/null || \
           echo -n "$value" | gcloud secrets versions add "$secret_name" --data-file=- 2>/dev/null; then
            SECRET_NAMES+=("$secret_name")
        fi
    done < .env
    
    # Build secret references dynamically
    for secret in "${SECRET_NAMES[@]}"; do
        # Map DATABASE_ prefixed secrets back to expected env var names
        env_name=${secret#DATABASE_}
        if [ -z "$SECRET_REFS" ]; then
            SECRET_REFS="${env_name}=${secret}:latest"
        else
            SECRET_REFS="${SECRET_REFS},${env_name}=${secret}:latest"
        fi
    done
    
    echo "✅ Secrets uploaded to GCP Secret Manager with proper permissions"
    echo "🔗 Secret references: $SECRET_REFS"
fi

# Deploy to Cloud Run with secret references
echo "🚀 Deploying to Cloud Run..."
if [ -n "$SECRET_REFS" ]; then
    echo "🔐 Using secrets: $SECRET_REFS"
    gcloud run deploy ${SERVICE_NAME} \
        --image ${IMAGE_NAME} \
        --platform managed \
        --region ${REGION} \
        --allow-unauthenticated \
        --port 8080 \
        --memory 2Gi \
        --cpu 1 \
        --concurrency 80 \
        --min-instances 0 \
        --max-instances 10 \
        --timeout 300 \
        --execution-environment gen2 \
        --set-env-vars "FLASK_ENV=production,BACKEND_VERSION=${BACKEND_VERSION},API_VERSION=${API_VERSION},FRONTEND_VERSION=${FRONTEND_VERSION},ORCA_VERSION=${ORCA_VERSION}" \
        --set-secrets "$SECRET_REFS"
else
    echo "⚠️  No secrets found, deploying without secrets"
    gcloud run deploy ${SERVICE_NAME} \
        --image ${IMAGE_NAME} \
        --platform managed \
        --region ${REGION} \
        --allow-unauthenticated \
        --port 8080 \
        --memory 2Gi \
        --cpu 1 \
        --concurrency 80 \
        --min-instances 0 \
        --max-instances 10 \
        --timeout 300 \
        --execution-environment gen2 \
        --set-env-vars "FLASK_ENV=production,BACKEND_VERSION=${BACKEND_VERSION},API_VERSION=${API_VERSION},FRONTEND_VERSION=${FRONTEND_VERSION},ORCA_VERSION=${ORCA_VERSION}"
fi

# Get the service URL
SERVICE_URL=$(gcloud run services describe ${SERVICE_NAME} --region=${REGION} --format="value(status.url)")

echo "✅ Deployment complete!"
echo "🌐 Service URL: ${SERVICE_URL}"
echo ""
echo "🔗 API Endpoints:"
echo "   Health Check: ${SERVICE_URL}/health"
echo "   API Info: ${SERVICE_URL}/"
echo "   Recent Models: ${SERVICE_URL}/models/recent"
echo "   User Models: ${SERVICE_URL}/models/{user_id}"
echo "   Model Details: ${SERVICE_URL}/models/{user_id}/{model_id}"
echo "   Download OBJ: ${SERVICE_URL}/download/{user_id}/{model_id}/obj"
echo "   Download Image: ${SERVICE_URL}/download/{user_id}/{model_id}/image"
echo ""
echo "📋 To view logs:"
echo "gcloud logs tail --follow --project=${PROJECT_ID} --resource-names=${SERVICE_NAME}"
echo ""
echo "🔧 To test the deployment:"
echo "curl ${SERVICE_URL}/health"
echo "curl ${SERVICE_URL}/models/recent"

# Restore original directory
popd >/dev/null
